In [6]:
import numpy as np

In [7]:
gpas_as_list = [4.0, 3.2, 3.5]

In [8]:
gpas_as_list.append(4.0)

In [9]:
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

In [10]:
gpas_as_list.pop(3)

4.0

In [11]:
gpas_as_list

[4.0, 3.2, 3.5]

In [12]:
gpas_as_list.insert(2,3.76)

In [13]:
gpas_as_list

[4.0, 3.2, 3.76, 3.5]

In [14]:
gpas_as_list.insert(1,"kosong")

In [15]:
gpas_as_list

[4.0, 'kosong', 3.2, 3.76, 3.5]

In [16]:
gpas_as_list.pop(1)

'kosong'

In [17]:
gpas_as_list

[4.0, 3.2, 3.76, 3.5]

**Numppy Array**

In [18]:
gpas = np.array(gpas_as_list)
gpas

array([4.  , 3.2 , 3.76, 3.5 ])

**Study Log**

membuat dumy array sebanyak 100

In [19]:
study_minutes = np.zeros(100)
study_minutes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
%whos

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list    list       n=4
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os              module     <module 'os' from 'C:\\Us<...>\\Python310\\lib\\os.py'>
study_minutes   ndarray    100: 100 elems, type `float64`, 800 bytes
sys             module     <module 'sys' (built-in)>


Mengubah tipe data float menjadi int yang membuat ukuran bytes nya berkurang dari 800 menjadi 200

In [21]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [22]:
%whos

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list    list       n=4
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os              module     <module 'os' from 'C:\\Us<...>\\Python310\\lib\\os.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes
sys             module     <module 'sys' (built-in)>


**Array Multi dimensi**

In [23]:
students_gpas = np.array([
                           [4.0, 3.3, 3.5, 4.0],
                           [3.96, 3.92, 4.0, 4.0],
                           [3.2, 3.8, 4.0, 4.0]
], np.float16)
students_gpas

array([[4.  , 3.3 , 3.5 , 4.  ],
       [3.96, 3.92, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

melihat dimensi dan elemen array

In [24]:
students_gpas.ndim

2

In [25]:
students_gpas.shape

(3, 4)

terdapat tiga array dan isinya masing-masing memiliki 4 elemen

In [26]:
students_gpas[2]

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [27]:
students_gpas[2][3]

4.0

**Study Log MultiDimensi**

In [28]:
study_minutes = np.array([
                          study_minutes,
                          np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [29]:
study_minutes[1][0] =  60
study_minutes

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=uint16)

In [30]:
rand =  np.random.RandomState(42)
fake_log =  rand.randint(30,180, size = 100, dtype=np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [31]:
fake_log[[3,8]]

array([44, 50], dtype=uint16)

In [32]:
index = np.array([
                  [3,8],
                  [16,24]
])

fake_log[index]

array([[ 44,  50],
       [139,  82]], dtype=uint16)

In [33]:
study_minutes = np.append(
                          study_minutes,
                          [fake_log]
)
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [34]:
rand =  np.random.RandomState(42)
fake_logs =  rand.randint(30,180, size = 100, dtype=np.uint16)
fake_logs

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)