In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
z = np.zeros(6)
z

array([0., 0., 0., 0., 0., 0.])

In [4]:
o = np.ones(6)
o

array([1., 1., 1., 1., 1., 1.])

In [5]:
print(np.arange(4))
print(np.arange(0,10,2)) #(start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [6]:
print(np.arange(2,29,5))

[ 2  7 12 17 22 27]


In [7]:
arr = np.array([1,2,3,4,5,6,7,8])

In [8]:
np.append(arr,[1,2]) #(nama_array,[value])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [9]:
np.delete(arr,1) #(nama_array, index)

array([1, 3, 4, 5, 6, 7, 8])

In [10]:
array_example = np.array([
    [
        [0,1,2,3],
        [4,5,6,7]
    ],

    [
        [0,1,2,3],
        [4,5,6,7]
    ],
    [
        [0,1,2,3],
        [4,5,6,7]
    ]
])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [11]:
array_example.ndim

3

In [12]:
array_example.size

24

In [13]:
array_example.shape

(3, 2, 4)

In [14]:
array_one = np.array([[1,2,3,4,5]])

In [15]:
array_one.ndim

2

In [16]:
array_one.size

5

In [17]:
array_one.shape

(1, 5)

In [18]:
a_new = np.arange(6)
a_new

array([0, 1, 2, 3, 4, 5])

In [19]:
b_new = a_new.reshape(3,2)
b_new

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
a_new.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [21]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [25]:
a2 = a[np.newaxis]
print(a2.shape)
a2

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [26]:
row_vector = a[np.newaxis,:]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [27]:
col_vector = a[:,np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [30]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [32]:
b = np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [34]:
c = np.expand_dims(a,axis=0)
c.shape

(1, 6)

In [35]:
data = np.array([1,2,3])
print(data)
print(data[0])
print (data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [41]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [38]:
five_up = (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [39]:
divisible_by_2 = a[a%2==0] 
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [43]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [45]:
arr = np.array ([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [46]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [47]:
a_1 = np.array([[1, 1],
                 [2, 2]])

In [49]:
a_2 = np.array ([[3, 3],
           [4, 4]])

In [51]:
np.vstack((a_1, a_2)) #Menumpuk array secara vertikal

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [52]:
np.hstack((a_1, a_2)) #menumpuk array secara horizontal

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [53]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [54]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [56]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a = np.array([1,2,3,4,])
a.sum()

10

In [60]:
b = np.array([[1,2],[4,3]])
b

array([[1, 2],
       [4, 3]])

In [61]:
b.sum(axis=0)

array([5, 5])

In [62]:
b.sum(axis=1)

array([3, 7])

In [63]:
data = np.array([1,2])
data

array([1, 2])

In [64]:
ones = np.ones(2)
ones

array([1., 1.])

In [65]:
data + ones

array([2., 3.])

In [66]:
data*data

array([1, 4])

In [67]:
data/data

array([1., 1.])

In [68]:
data * 2

array([2, 4])

In [69]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
          [0.54627315, 0.05093587, 0.40067661, 0.55645993],
          [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [70]:
A.sum()

4.8595784

In [73]:
A.min()

0.05093587

In [75]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [77]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [78]:
A.max()

0.82485143

In [79]:
A.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [80]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [81]:
A.std()

0.21392120766089617

In [83]:
print(np.zeros((3,2)))#3 list dengan 2 elemen
print(np.ones((3,2)))
print(np.random.random((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.07384516 0.76178409]
 [0.71459591 0.40831846]
 [0.19215282 0.36013384]]


In [84]:
data=np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [85]:
ones = np.ones([2,2])
ones

array([[1., 1.],
       [1., 1.]])

In [86]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [88]:
ones_row = np.ones([1,2])
ones_row

array([[1., 1.]])

In [89]:
print(data+ones_row)

[[2. 3.]
 [4. 5.]]


In [90]:
a_1 = np.array ([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)
a_2 = np.array ([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [91]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

In [92]:
data = np.array([[1,2],[3,4],[5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [93]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [94]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [95]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [96]:
print(data.T)#T kebalikan dari shape suatu array misal awal (3,2) -> 3 array 2 elemen menjadi (2,3) -> 2 array 3 elemen

[[1 3 5]
 [2 4 6]]


In [97]:
data_col = np.array ([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [98]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
arr = np.arange(6).reshape((3,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [103]:
ndarr = np.array([[[1,2], [3,4]],
[[5,6],[7,8]]])
ndarr   

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [108]:
print(ndarr[0,1,1])

4


In [110]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [111]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [112]:
print(np.random.random((4,3,2)))

[[[0.8135178  0.94824003]
  [0.40435133 0.64388867]
  [0.53000982 0.10536643]]

 [[0.20166325 0.95966661]
  [0.12664404 0.39541378]
  [0.61363969 0.56849038]]

 [[0.75447972 0.76391927]
  [0.88179164 0.86621601]
  [0.39471486 0.57593734]]

 [[0.4203022  0.92549615]
  [0.21049936 0.8458718 ]
  [0.48766781 0.28995258]]]


In [113]:
arrflat = np. array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [114]:
arrflat.flatten() #flatten digunakan untuk meratakan array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction))
